# arguments for dataset
dataset: pascal
nclass: 21
crop_size: 321
data_root: /data/VOC2012

# arguments for training
epochs: 80
batch_size: 4 # per GPU x 4 GPUs
lr: 0.001
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
em_loss_weight: 0.07
loss_last: 0.0001
# arguments for model
model: deeplabv3plus
backbone: resnet50
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
